"use client";

import { CloudSun, Droplets, Eye, Thermometer, Wind } from "lucide-react";
import { useSimulation } from "@/hooks/useSimulation";
import { Panel, PanelHeading } from "@/components/ui/Panel";
import { Select } from "@/components/ui/Select";

const directions = ["N", "NE", "E", "SE", "S", "SW", "W", "WNW", "NW"];
const stabilities = [["A", "Very unstable"], ["B", "Unstable"], ["C", "Slightly unstable"], ["D", "Neutral"], ["E", "Stable"], ["F", "Very stable"]];

export function WeatherPanel() {
  const { scenario, setScenarioField } = useSimulation();
  const weather = scenario.weather;
  return <Panel className="rail-panel weather-panel"><PanelHeading><span>WEATHER INPUT</span><span className="simulated-badge">SIMULATED</span></PanelHeading><div className="weather-primary"><Wind size={17} /><strong>{weather.windSpeedKmh} km/h {weather.windDirection}</strong><span>sample surface wind</span></div><div className="weather-grid"><div><CloudSun size={14} /><span>Stability</span><strong>{weather.stability}</strong></div><div><Thermometer size={14} /><span>Temperature</span><strong>{weather.temperatureC}°C</strong></div><div><Droplets size={14} /><span>Humidity</span><strong>{weather.humidityPercent}%</strong></div><div><Eye size={14} /><span>Visibility</span><strong>{weather.visibilityKm} km</strong></div></div><div className="weather-edit"><label>Wind speed<input aria-label="Wind speed" type="number" min="0" max="150" step="1" value={weather.windSpeedKmh} onChange={(event) => setScenarioField("weather.windSpeedKmh", Number(event.target.value))} /><span className="field-unit">km/h</span></label><label>Direction<Select aria-label="Wind direction" value={weather.windDirection} onChange={(event) => setScenarioField("weather.windDirection", event.target.value)}>{directions.map((direction) => <option key={direction}>{direction}</option>)}</Select></label><label>Temperature<input aria-label="Temperature" type="number" min="-60" max="60" step="1" value={weather.temperatureC} onChange={(event) => setScenarioField("weather.temperatureC", Number(event.target.value))} /><span className="field-unit">°C</span></label><label>Humidity<input aria-label="Humidity" type="number" min="0" max="100" step="1" value={weather.humidityPercent} onChange={(event) => setScenarioField("weather.humidityPercent", Number(event.target.value))} /><span className="field-unit">%</span></label><label>Stability<Select aria-label="Atmospheric stability" value={weather.stability} onChange={(event) => setScenarioField("weather.stability", event.target.value)}>{stabilities.map(([value, label]) => <option value={value} key={value}>{value} · {label}</option>)}</Select></label><label>Precipitation<input aria-label="Precipitation" type="number" min="0" max="500" step="0.1" value={weather.precipitationMm} onChange={(event) => setScenarioField("weather.precipitationMm", Number(event.target.value))} /><span className="field-unit">mm</span></label></div><p className="estimate-note">Sample weather only. No live weather service is connected.</p></Panel>;
}
